apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - prometheus-configmap.yaml
  - prometheus-alerts-configmap.yaml
  - prometheus-deployment.yaml
  - prometheus-service.yaml
  - alertmanager-configmap.yaml
  - alertmanager-deployment.yaml
  - alertmanager-service.yaml
  - grafana-provisioning-configmap.yaml
  - grafana-dashboards-configmap.yaml
  - grafana-deployment.yaml
  - grafana-service.yaml
